---
title: "notebook"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Seurat)
library(dplyr)
library(patchwork)
library(ggplot2)
theme_set(theme_minimal())
```

```{r}
#test
fig <- function(width, heigth){
     options(repr.plot.width = width, repr.plot.height = heigth)
}
```

```{r}
# load data: barcode, genes, and counts
sc3_data <- Read10X(data.dir = 'input')
```

```{r}
# init Seurat object with raw counts
sc3 <- CreateSeuratObject(
  counts = sc3_data, project = "SC3v3", min.cells = 3, min.features = 200
  )
```

```{r}
# view data
sc3
sc3_data[1:5, 1:10]
```

```{r}
# find % mitochondrial DNA
sc3[["percent.mt"]] <- PercentageFeatureSet(sc3, pattern = "^MT-")
```

```{r}
# check mitochondrial percentages => violin plot of dataset quality
fig(16,9)
VlnPlot(sc3, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

```{r}
# Normalize read counts
sc3 <- NormalizeData(
  sc3, normalization.method = "LogNormalize", scale.factor = 10000
  )
```

```{r}
# Find top 500 most variable features
sc3 <- FindVariableFeatures(sc3, selection.method = "vst", nfeatures = 500)

# 10 most variable genes
top10_genes <- head(VariableFeatures(sc3), 10)
top10_genes
```

```{r}
# Plot variable genes and label top 10
plot1 <- LabelPoints(
  plot = plot1, points = top10_genes, repel = TRUE, xnudge = -0.8, ynudge = 0
  )
plot1
```

```{r}
# Scaling for PCA
genes_names <- rownames(sc3)
sc3 <- ScaleData(sc3, features = genes_names, verbose = FALSE)
```

```{r}
# PCA
fig(16, 11)
sc3 <- RunPCA(
  sc3, features = VariableFeatures(object = sc3), npcs = 50, verbose = FALSE
  )

# Top 10 most important up/downreg for 1-5PCs
print(sc3[["pca"]], dims = 1:5, nfeatures = 10) 

# Plot first 5 loadings
VizDimLoadings(sc3, dims = 1:6, reduction = "pca", ncol = 3)
```

```{r}
# % variance by PC
mat <- GetAssayData(sc3, assay = "RNA", slot = "scale.data")
pca <- sc3[["pca"]]

# total variance
total_variance <- sum(matrixStats::rowVars(mat))

eigValues <- (pca@stdev)^2
varExplained <- eigValues / total_variance

# print variance explained by first 2 PCs
scales::label_percent()(round(sum(varExplained[c(1,2)]), 4))

```

```{r}
fig(14, 10)

# variance explained by PC in DF
var_explained_df <- tibble(pc_number = 1:length(varExplained), var_explained = cumsum(varExplained))

# elbow plot of variance explained by PC
ggplot(var_explained_df, aes(x = pc_number, y = var_explained)) +
geom_point(size = 2) +
geom_line(size = 0.8) +
scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
labs(title = "Cumulative Variance Explained by the first 50 PCs",
    x = "PC",
    y = "Cumulative Variance explained") +
theme_bw() +
theme(plot.title = element_text(size = 14),
          plot.subtitle = element_text(size = 10),
          axis.text.x= element_text(size = 10),
          axis.text.y= element_text(size = 10), 
          axis.title=element_text(size = 10))
```

```{r}
# dimplot: plot PC1 & PC2
fig(14, 10)
DimPlot(sc3, reduction = "pca", dims = c(1,2))
```


